name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        working-directory: AppSourceCode

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: AppSourceCode

      - name: Run Lint
        run: ./gradlew lintDebug
        working-directory: AppSourceCode

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
        working-directory: AppSourceCode

      - name: Run Unit Tests New
        run: ./gradlew testDebugUnitTest
        working-directory: AppSourceCode

      - name: Generate Code Coverage Report
        run: ./gradlew koverXmlReport
        working-directory: AppSourceCode

      - name: Upload Coverage Report
        uses: actions/upload-artifact@v4
        with:
          name: code-coverage-report
          path: AppSourceCode/app/build/reports/kover/report.xml

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: debug-apk
          path: AppSourceCode/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload Lint Report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: AppSourceCode/app/build/reports/lint-results-debug.html

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: AppSourceCode/app/build/reports/tests/testDebugUnitTest/
